#k3s/kustomization/image-repository.yaml 
apiVersion: image.toolkit.fluxcd.io/v1beta2
#apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: dknotes-laravel
  namespace: flux-system
spec:
  image: local-reg.dk.lab:5000/dknotes-laravel
  interval: 2m
  insecure: true
  secretRef:
    name: registry-auth
  certSecretRef:
    name: registry-ca
