# k3s/kustomization/image-policy.yaml
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: dknotes-laravel
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: dknotes-laravel
  policy:
    semver:
      range: ">=1.0.0"

