# k3s/kustomization/image-update-automation.yaml
apiVersion: image.toolkit.fluxcd.io/v1
#beta1
kind: ImageUpdateAutomation
metadata:
  name: dknotes-laravel
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: laravel-k3s
    commit:
      author:
        name: fluxbot
        email: fluxbot@local
      messageTemplate: |
        🤖 [automated] Update container images
        
        {{ range $resource, $changes := .Changed.Objects -}}
        {{ $resource.Kind }}/{{ $resource.Name }}:
        {{ range $_, $change := $changes -}}
        - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
    push:
      branch: laravel-k3s
  update:
    path: ./k3s/kustomization
    strategy: Setters

# explicacion
# interval: 5m → Cada 5 minutos, escanea si hay nuevas imágenes
# path: ./k3s/kustomization → Busca YAMLs para actualizar en esta carpeta
# messageTemplate → Mensaje de commit que usará Flux
