apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dknotes-ingress
  namespace: dknotes 
spec:
  ingressClassName: traefik
  rules:
  - host: dknotes.datenmaniak.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dknotes-service
            port:
              number: 80
  # ↑ CONSERVA LO ANTERIOR Y AÑADE ESTO:
  tls:
  - hosts:
      - dknotes.local
    secretName: dknotes-tls-secret
