# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dknotes

# Secret TLS manual
secretGenerator:
- name: dknotes-tls-secret
  type: kubernetes.io/tls
  files:
    - tls.crt=dknotes.local.pem 
    - tls.key=dknotes.local-key.pem

# Recursos
resources:
  - ns.yaml
  - secret.yaml
  - pv-pvc-nfs-persistence.yaml
  - deploy.yaml
  - webservice.yaml
  - ingress.yaml

configMapGenerator:
- name: nginx-config
  files:
    - default.conf
