apiVersion: v1
kind: Secret
metadata:
  name: dknotes-secrets
  namespace: dknotes
type: Opaque
stringData:
  username: "dkuser"
  password: "7shogun"
  app_key: "base64:8XihyVNRB4G/X34ZebjGkdUDGceAyADHyrTnNMPGYkk="