# Usamos PHP 8.3 FPM sobre Alpine para mínima huella de seguridad y tamaño
FROM php:8.3-fpm-alpine

# Instalamos dependencias de sistema necesarias para PostgreSQL y utilidades
RUN apk add --no-cache \
    postgresql-dev \
    libpng-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl

# Instalamos extensiones de PHP (pdo_pgsql es vital para tu base de datos)
RUN docker-php-ext-install pdo pdo_pgsql pgsql gd zip

# Instalamos Composer (Cerebro de dependencias de Laravel)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configuramos el directorio de trabajo dentro del contenedor
WORKDIR /var/www

# Ajustamos permisos para que el usuario de PHP pueda escribir en storage (clave en Laravel)
RUN chown -R www-data:www-data /var/www/

# Exponemos el puerto 9000 para que Nginx pueda conectarse vía FastCGI
EXPOSE 9000

CMD ["php-fpm"]
