apiVersion: v1
kind: Secret
metadata:
  name: dknotes-secrets
  namespace: dknotes
type: Opaque
stringData:
  username: "user"
  password: "pass"
  app_key: "base64:8XihyVNRB4G/X34ZebjGkdUDGceAyADHyrTnNMPGYkk="