name: Integración Continua (CI) - dk-notes

# 1. DISPARADORES: Cuándo se ejecuta esta receta
on:
  push:
    # branches: [ "design/fix", "laravel-k3s","main", "develop" ]
    branches: [ "design/fix","main", "develop" ]
  pull_request:
    branches: [ "design/fix", "main" ]
    # branches: [ "laravel-k3s", "main" ]

# 2. TRABAJOS: Qué va a hacer la máquina virtual
jobs:
  laravel-tests:
    runs-on: ubuntu-latest # El sistema operativo base en la nube

    steps:
      # Paso 1.1 y 1.2: Clonar el código del repositorio en la máquina virtual
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      # Paso 1.4: Configurar el entorno de PHP 8.3 y extensiones de forma automatizada
      - name: Configurar PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, json, pdo_sqlite
          tools: composer:v2
          coverage: none

      # Paso extra de control: Verificar que las versiones sean correctas en los logs
      - name: Validar versiones del entorno
        run: |
          php -v
          composer --version
      # ----- FASE II  ---- #
      # Paso 2.1: Gestión Inteligente de Dependencias (Instalación + Caché)
      # Nota: La acción 'shivammathur/setup-php' que usamos en la Fase 1 ya maneja 
      # la caché de Composer automáticamente de fondo si se lo indicamos.

      # ---- utilizado para troubleshooting del composer
      # composer install --prefer-dist --no-progress --no-interaction --ignore-platform-reqs --no-scripts
      # php artisan package:discover --ansi 
          # composer config platform.php 8.3.0

      - name: Instalar Dependencias de PHP (Composer)
        working-directory: ./app
        run: |
          composer install --prefer-dist --no-progress --no-interaction
        


      # Paso 2.2: El Guardián del Estilo (Laravel Pint)
      # Ejecuta el linter en modo prueba. Si encuentra errores de formato, rompe el pipeline.
      - name: Validar Estilo de Código (Laravel Pint)
        working-directory: ./app
        run: ./vendor/bin/pint --test

      # Paso 2.3: El Escáner de Vulnerabilidades (Composer Audit)
      # Revisa que ninguna librería de terceros en tu composer.lock tenga fallos de seguridad conocidos.
      - name: Auditar Seguridad de Dependencias
        working-directory: ./app
        run: |
          composer audit